name: intaranfashion_mobile
version: 1.0.0+1
publish_to: none
description: Aplikasi pencatatan transaksi create by Intaran Fashion.
environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'

dependencies:
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_staggered_grid_view: ^0.6.2
  get: 4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.3
  horizontal_data_table: ^4.1.1
  intl: ^0.17.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/intaran.png
    - assets/report.png
    - assets/settings.png
    - assets/transaction.png
    - assets/table.png
    - assets/noimage.png
    - assets/tambahbarang.png
    - assets/outcome.png
    - assets/datapayment.png
    - assets/payment.png
    - assets/tabledua.png
    - assets/tabletiga.png
    - assets/pencil.png
    - assets/google.png
